[environment]
width = 500
height = 500

[ant]
stepsize = 7

[pheromone]
lifeexpectancy = 30

[graphics]
ant.radius = 2
ant.scouting_colour = "#AF0220"
ant.notscouting_colour = "#3BC302"
environment.backgroundcolour = "#F4F2F0" # Dark mode: "#000028"
food.ini_colour = "#00C8C8"
nest.radius = 20
nest.colour = "#F27E1D"
pheromone.radius = 0.1
pheromone.colour = "#050994"

